version: '3.8'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantasycalendar
    volumes:
      - pgdata:/var/lib/postgresql/data

  calendar-engine:
    build: ./calendar-engine
    ports:
      - "5001:5000"
    volumes:
      - ./calendar-engine:/app

  test:
    build: ./calendar-engine
    command: ["pytest", "tests/"]
    volumes:
      - ./calendar-engine:/app
    depends_on:
      - db

volumes:
  pgdata:
