version: '3.8'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantasycalendar
    volumes:
      - pgdata:/var/lib/postgresql/data

  calendar-engine:
    build: ./calendar-engine
    ports:
      - "5001:5000"

volumes:
  pgdata:
